import { PageCategory } from './types';

export const n5: PageCategory[] = [
  {
    title: 'JLPT N5',
    subtitle: 'Begin your journey here!',
    tasks: [
      'no',
      'da-desu',
      'chyaikenai',
      'dake',
      'darou',
      'de',
      'demo',
      'deshou',
      'donna',
      'doushite',
      'douyatte',
      'ga',
      'ga-arimasu',
      'ga-hoshii',
      'ga-imasu',
      'hou-ga-ii',
      'i-adjectives',
      'ichiban',
      'issho-ni',
      'itsumo',
      'janai-dewa-nai',
      'ka-question',
      'ka-ka',
      'kara',
      'kata',
      'kedo',
      'keredo-mo',
      'mada',
      'mada-te-imasen',
      'made',
      'mae-ni',
      'masen-ka',
      'mashou',
      'mashouka',
      'mo',
      'mou',
      'na-adjectives',
      'naa',
      'naide',
      'naide-kudasai',
      'naito-ikenai',
    ],
  },
];
